
###
POST http://localhost:8080/api/heart
Content-Type: application/json
Access-Token: Bearer {{auth_token}}
Refresh-Token: Bearer {{refresh_token}}

{
  "postId": 1,
  "memberId": 1,
  "commentId": 1
}